version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/db
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
